feat: P4ADEV-1674 create DP in ACA
pagopa/p4pa-pagopa-payments pull request #2
Opened 2024-12-19 15:06 UTC by serdimic

#### Description

Implement API to create a debt position in ACA

#### List of Changes

Implement API to create a debt position in ACA

#### Motivation and Context

Support ACA

#### How Has This Been Tested?

- Pre-Deploy Test
  - [X] Unit
  - [ ] Integration (Narrow)
- Post-Deploy Test
  - [ ] Isolated Microservice
  - [ ] Broader Integration
  - [ ] Acceptance
  - [ ] Performance & Load

#### Types of changes

- [ ] PATCH - Bug fix (backwards compatible bug fixes)
- [X] MINOR - New feature (add functionality in a backwards compatible manner)
- [ ] MAJOR - Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] CHORE - Minor Change (fix or feature that don't impact the functionality e.g. Documentation or lint configuration)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2025-01-08 18:10 UTC, antonioT90 requested changes

2025-01-08 18:10 UTC, antonioT90 commented on build.gradle.kts
> +  modelPackage.set("it.gov.pagopa.pu.p4pa-debt-positions.dto.generated")
```suggestion
  apiPackage.set("it.gov.pagopa.pu.debtpositions.controller.generated")
  modelPackage.set("it.gov.pagopa.pu.debtpositions.dto.generated")
```

2025-01-08 18:10 UTC, antonioT90 commented on build.gradle.kts
> +  modelPackage.set("it.gov.pagopa.pu.p4pa-organization.dto.generated")
```suggestion
  apiPackage.set("it.gov.pagopa.pu.organization.controller.generated")
  modelPackage.set("it.gov.pagopa.pu.organization.dto.generated")
```

2025-01-08 18:10 UTC, antonioT90 commented on openapi/p4pa-pagopa-payments.openapi.yaml
> +        uniqueIdentifierCode:
```suggestion
        entityType:
          type: string
        fiscalCode:
```

2025-01-08 18:10 UTC, antonioT90 commented on openapi/p4pa-pagopa-payments.openapi.yaml
> +        - uniqueIdentifierType
```suggestion
        - fiscalCode
        - entityType
```

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/AcaClientImpl.java
can we change apiKey handling with the ThreadLocal which will store just the apiKey instead the entire ApiClient object?

Actually you are still changing the instance variable acaApi used by all threads

2025-01-08 18:10 UTC, antonioT90 commented on src/main/resources/application.yml
> +app:
can we use the same property names used in pu-bff?

rest-client:
   default-timeouts:...

2025-01-08 18:10 UTC, antonioT90 commented on src/main/resources/application.yml
> +    base-url: "\${ACA_BASE_URL:}"
set this variable on helm project (see pu-bff for auth and organization URL)

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/DebtPositionClientImpl.java
> +      () -> "getDebtPositionTypeOrgById[%s]".formatted(debtPositionTypeOrgId)
why should this be a supplier if it will just depends on method parameters? it could be directly a String (it would be a lambda (a Function) if you should build the String using some info provided to the lambda parameters)

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +    final AtomicReference<DebtPositionTypeOrg> debtPositionTypeOrg = new AtomicReference<>();
why don't you directly retrieve it instead of perform the invoke inside the loop?

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +      paymentOption.getInstallments().forEach(installment -> {
instead of having for loops intended to fill a List, let's use stream API to directly build the list
```suggestion
    return debtPosition.getPaymentOptions().stream()
      .flatMap(paymentOption -> paymentOption.getInstallments().stream())
      .filter(this::installment2skip) // inside this method you should move the if/return logic below
      .map(installment -> {
         ...
         return new request...
         })
         .toList();
```

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +  public final static OffsetDateTime MAX_DATE = LocalDateTime.of(2099,12,31,23,59,59).atZone(ZoneId.of("Europe/Rome")).toOffsetDateTime();
there is already a constant for this java.time.LocalDateTime#MAX

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +  public List<NewDebtPositionRequest> mapToNewDebtPositionRequest(DebtPositionDTO debtPosition, Set<String> filterInstallmentStatus, String accessToken) {
why should the status to skip be a parameter and not a constant of this class?

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +          log.info("ACA mapToNewDebtPositionRequest: ignoring installment [{}/{}] beacuse has multiple transfer[{}]",
maybe a warn level could be better?

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/service/broker/BrokerService.java
> +      log.error("organization not found [{}]",organizationId);
this would be logged also by the exception handler, right?

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/util/RestUtil.java
> +  public static <T> T handleRestException(Supplier<T> in, Supplier<String> logErrorDetail, boolean logElapsed) {
```suggestion
  public static <T> T handleRestException(Supplier<T> invoker, Supplier<String> logErrorDetail, boolean logElapsed) {
```

2025-01-08 18:10 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/util/RestUtil.java
> +    } catch (HttpServerErrorException he) {
could be useful to catch NotFound to return null?

2025-01-09 08:43 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/AcaClientImpl.java
refactored apiKey handling in a similar way of MS organization/debtPosition API client. Unfortunately the generated openapi code in case of "apiKey" auth (used on paCreatePosition API) is different from generated openapi code in case of "bearer token" auth (used on organization/debtPosition API), and does not expose a method for setting apiKey using a supplier.
Therefore i made a (hopefully not too bad) workaround, using a wrapper ApiClient class that override api-key handling.

2025-01-09 08:48 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +  public List<NewDebtPositionRequest> mapToNewDebtPositionRequest(DebtPositionDTO debtPosition, Set<String> filterInstallmentStatus, String accessToken) {
The rationale is that the mapper is a pure converter/executor. The service instead determines - based on whatever rule (in this case is a hardcoded constant) - what are the correct status to handle.
This way, if in future we would like to change something in this behaviour (or just review), we know that we should check out the service class, and not the mapper.

2025-01-09 08:49 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +          log.info("ACA mapToNewDebtPositionRequest: ignoring installment [{}/{}] beacuse has multiple transfer[{}]",
done

2025-01-09 08:50 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/service/broker/BrokerService.java
> +      log.error("organization not found [{}]",organizationId);
removed a useless log message

2025-01-09 08:53 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/util/RestUtil.java
> +  public static <T> T handleRestException(Supplier<T> in, Supplier<String> logErrorDetail, boolean logElapsed) {
done

2025-01-09 09:03 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/util/RestUtil.java
> +    } catch (HttpServerErrorException he) {
not sure, it depends on the business logic of the caller; on the other ends, since as of now in the code there is no specific handling of notFound, this new behaviour can be introduced without side-effect, so I made this handling and committed it.
Just not sure if the NotFound is internally handled by Spring returning HttpClientErrorException.NotFound.

2025-01-09 12:19 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/AcaClientImpl.java
ok, the apiKey is constant per organization, while bearer will change frequently...
maybe we could store a map having the apiKey as key and the AcaClient as value?

2025-01-09 13:54 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/AcaClientImpl.java
done

2025-01-09 14:06 UTC, serdimic commented on src/main/resources/application.yml
> +app:
done

2025-01-09 14:17 UTC, serdimic commented on src/main/resources/application.yml
> +    base-url: "\${ACA_BASE_URL:}"
done

2025-01-09 14:30 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/DebtPositionClientImpl.java
> +      () -> "getDebtPositionTypeOrgById[%s]".formatted(debtPositionTypeOrgId)
done

2025-01-09 14:33 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +    final AtomicReference<DebtPositionTypeOrg> debtPositionTypeOrg = new AtomicReference<>();
because in some cases (the if-then statement above that point in the code) there is no need to perform a potentially time-consuming REST operation to retrieve the DebtPositionTypeOrg

2025-01-09 14:48 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +      paymentOption.getInstallments().forEach(installment -> {
done

2025-01-09 14:55 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +  public final static OffsetDateTime MAX_DATE = LocalDateTime.of(2099,12,31,23,59,59).atZone(ZoneId.of("Europe/Rome")).toOffsetDateTime();
LocalDateTime.MAX is '+999999999-12-31T23:59:59.999999999'. I don't think it's a good idea to use this date to pass to PagoPA node and set it as expiration date; I think it's better to have control of this date (in case, it could even become a configuration param).

2025-01-09 15:22 UTC, antonioT90 commented on helm/values.yaml
> +    NODE_ACA_BASE_URL: "https://api.uat.platform.pagopa.it"
this URL will change based on the environment, you should set inside each values-<ENV>.yml with the proper value

2025-01-09 15:22 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/AcaClientImpl.java
> +      ApiClient apiClient = new ApiClient(restTemplateBuilder.build());
build the RestTemplate once on the constructor instead of building it each time

2025-01-09 15:22 UTC, antonioT90 commented on src/main/resources/application.yml
> +  node:
```suggestion
  pagopa-node-services:
```

2025-01-09 15:22 UTC, antonioT90 commented on src/main/resources/application.yml
> +      base-url: "\${NODE_ACA_BASE_URL:}"
```suggestion
      base-url: "\${PAGOPA_NODE_ACA_BASE_URL:}"
```

2025-01-09 15:22 UTC, antonioT90 commented on helm/values.yaml
> +    NODE_ACA_BASE_URL: "https://api.uat.platform.pagopa.it"
ps: i'm suggesting to you the name PAGOPA_NODE_ACA_BASE_URL

2025-01-09 15:22 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +  public List<NewDebtPositionRequest> mapToNewDebtPositionRequest(DebtPositionDTO debtPosition, Set<String> filterInstallmentStatus, String accessToken) {
For me, the mapper is building the request given the installment, so it should know what should or should not be sent, so the statuses list should be know just to it

2025-01-09 15:28 UTC, serdimic commented on helm/values.yaml
> +    NODE_ACA_BASE_URL: "https://api.uat.platform.pagopa.it"
done

2025-01-09 15:30 UTC, serdimic commented on src/main/resources/application.yml
> +      base-url: "\${NODE_ACA_BASE_URL:}"
done

2025-01-09 15:30 UTC, serdimic commented on src/main/resources/application.yml
> +  node:
done

2025-01-09 15:32 UTC, antonioT90 requested changes

2025-01-09 15:32 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/util/RestUtil.java
> +    } catch (HttpServerErrorException he) {
that's right, it will throw exactly this exception (org.springframework.web.client.HttpClientErrorException$NotFound)

2025-01-09 15:32 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +    final AtomicReference<DebtPositionTypeOrg> debtPositionTypeOrg = new AtomicReference<>();
as actually changed, you are performing the REST each time, if someone is calling ACA service is to really call it, so I think that the 99,9999% we are interested on executing it.

2025-01-09 15:32 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/connector/AcaClientImpl.java
> +      ApiClient apiClient = new ApiClient(restTemplateBuilder.build());
done

2025-01-09 15:39 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/mapper/AcaDebtPositionMapper.java
> +  public List<NewDebtPositionRequest> mapToNewDebtPositionRequest(DebtPositionDTO debtPosition, Set<String> filterInstallmentStatus, String accessToken) {
ok no problem, done

2025-01-09 15:48 UTC, antonioT90 requested changes

2025-01-09 15:48 UTC, antonioT90 commented on src/main/java/it/gov/pagopa/pu/pagopapayments/service/aca/AcaService.java
> +  public static final Set<String> STATUS_TO_SEND_ACA = Set.of(STATUS_INSTALLMENT_TO_SYNCH);
I would move also the constant :)

2025-01-09 16:23 UTC, serdimic commented on src/main/java/it/gov/pagopa/pu/pagopapayments/service/aca/AcaService.java
> +  public static final Set<String> STATUS_TO_SEND_ACA = Set.of(STATUS_INSTALLMENT_TO_SYNCH);
done

2025-01-09 17:47 UTC, antonioT90 approved these changes

2025-01-09 17:48 UTC, merged